version: '3.8'
name: nooota

networks:
  nooota:
    driver: bridge
    name: nooota

services:
  postgres:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: backend
    networks:
      - nooota
    ports:
      - '5432:5432'
  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=password
    ports:
      - '6379:6379'
    volumes:
      - redis_volume:/var/lib/redis/data
    networks:
      - nooota
  minio:
    image: 'minio/minio:latest'
    ports:
      - '9000:9000'
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    volumes:
      - 'minio:/data/minio'
    command: 'minio server /data/minio --console-address ":9001"'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:9000/minio/health/live'
      retries: 3
      timeout: 5s
    networks:
      - nooota
  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: "postgres"  # Remplacez par l'adresse IP ou le nom du serveur de votre instance PostgreSQL
      DB_PORT: "5432"  # Port par défaut de PostgreSQL
      DB_DATABASE: "keycloak"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    command:
      - start-dev
    volumes:
      - keycloak_data:/path/to/keycloak/data
    networks:
      - nooota

volumes:
  minio:
  postgres_volume:
  redis_volume:
  keycloak_data:
