name: CI/CD Pipeline Staging

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  prepare-ci:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      pr-title: ${{ steps.pr-title.outputs.title }}
      version: ${{ steps.extract_version.outputs.result }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Get PR title
      id: pr-title
      env: 
        PR_TITLE: ${{ github.event.pull_request.title }}
      run: |
        echo "PR Title: $PR_TITLE"
        echo "title=$PR_TITLE" >> $GITHUB_OUTPUT
    - name: Extract version from PR body
      id: extract_version
      uses: actions/github-script@v6
      with:
        script: |
          const body = context.payload.pull_request.body
          console.log(body)
          const versionMatch = body.match(/- version:\s*(.*)/)
          if (!versionMatch) {
            throw new Error("No version specified in the PR body with pattern '- version: <version>'");
          }
          return versionMatch[1].trim().replace(/"/g, '')
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
    - name: Echo version
      # Echo the outputs version
      run: |
        echo "Version: ${{ steps.extract_version.outputs.result }}"
        echo "version=${{ steps.extract_version.outputs.result }}" >> $GITHUB_OUTPUT
  tag-repository:
    if: github.event.pull_request.merged == true
    needs: prepare-ci
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: noootaaa/backend
        ref: main
        token: ${{ secrets.PAT }}
    - name: Tag repository
      run: |
        git config user.name "GitHub Actions"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git tag -a "staging-${{ needs.prepare-ci.outputs.version }}" -m "Staging release"
        git push origin "staging-${{ needs.prepare-ci.outputs.version }}"
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
  build-and-push:
    if: github.event.pull_request.merged == true
    needs: prepare-ci
    uses: noootaaa/infrastructure/.github/workflows/docker-ci.yml@main
    with:
      image-name: backend
      repository: noootaaa/backend
      tag: "staging-${{ needs.prepare-ci.outputs.version }}"
    secrets:
      CONTAINER_REGISTRY_TOKEN: ${{ secrets.PAT }}
      CONTAINER_REGISTRY_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      CONTAINER_REGISTRY_ENDPOINT: ghcr.io
      PAT: ${{ secrets.PAT }}
